name: machinelearning2
channels:
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - pytorch
  - torchaudio
  - torchvision
  - flask
  - flask-cors
  - requests
  - pillow
  - matplotlib
  - sympy
  - pyyaml
  - jinja2
  - pip:
      - aiofiles
      - aiohttp
      - altair
      - anthropic
      - chromadb
      - fastapi
      - huggingface-hub
      - langchain
      - llama-index
      - llama-index-llms-ollama
      - openai
      - sentence-transformers
      - tiktoken
      - transformers
      - uvicorn
      - streamlit
      # Add any others you specifically need from your original list
